//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.05 at 10:03:40 CEST 
//

package net.sf.dozer.util.mapping.vo.jaxb.employee.impl;

public class EmployeeWithInnerClassTypeImpl implements net.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeWithInnerClassType,
    com.sun.xml.bind.JAXBObject, net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.UnmarshallableObject,
    net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.XMLSerializable,
    net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.ValidatableObject {

  protected java.util.Calendar _BirthDate;
  protected java.lang.String _FirstName;
  protected net.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeWithInnerClassType.AddressType _Address;
  protected java.lang.String _LastName;
  public final static java.lang.Class version = (net.sf.dozer.util.mapping.vo.jaxb.employee.impl.JAXBVersion.class);
  private static com.sun.msv.grammar.Grammar schemaFragment;

  private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
    return (net.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeWithInnerClassType.class);
  }

  public java.util.Calendar getBirthDate() {
    return _BirthDate;
  }

  public void setBirthDate(java.util.Calendar value) {
    _BirthDate = value;
  }

  public java.lang.String getFirstName() {
    return _FirstName;
  }

  public void setFirstName(java.lang.String value) {
    _FirstName = value;
  }

  public net.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeWithInnerClassType.AddressType getAddress() {
    return _Address;
  }

  public void setAddress(net.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeWithInnerClassType.AddressType value) {
    _Address = value;
  }

  public java.lang.String getLastName() {
    return _LastName;
  }

  public void setLastName(java.lang.String value) {
    _LastName = value;
  }

  public net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.UnmarshallingEventHandler createUnmarshaller(
      net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.UnmarshallingContext context) {
    return new net.sf.dozer.util.mapping.vo.jaxb.employee.impl.EmployeeWithInnerClassTypeImpl.Unmarshaller(context);
  }

  public void serializeBody(net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.XMLSerializer context)
      throws org.xml.sax.SAXException {
    context.startElement("", "FirstName");
    context.endNamespaceDecls();
    context.endAttributes();
    try {
      context.text(((java.lang.String) _FirstName), "FirstName");
    } catch (java.lang.Exception e) {
      net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.Util.handlePrintConversionException(this, e, context);
    }
    context.endElement();
    if (_BirthDate != null) {
      context.startElement("", "BirthDate");
      context.endNamespaceDecls();
      context.endAttributes();
      try {
        context.text(javax.xml.bind.DatatypeConverter.printDate(((java.util.Calendar) _BirthDate)), "BirthDate");
      } catch (java.lang.Exception e) {
        net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.Util.handlePrintConversionException(this, e, context);
      }
      context.endElement();
    }
    context.startElement("", "LastName");
    context.endNamespaceDecls();
    context.endAttributes();
    try {
      context.text(((java.lang.String) _LastName), "LastName");
    } catch (java.lang.Exception e) {
      net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.Util.handlePrintConversionException(this, e, context);
    }
    context.endElement();
    context.startElement("", "Address");
    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Address), "Address");
    context.endNamespaceDecls();
    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Address), "Address");
    context.endAttributes();
    context.childAsBody(((com.sun.xml.bind.JAXBObject) _Address), "Address");
    context.endElement();
  }

  public void serializeAttributes(net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.XMLSerializer context)
      throws org.xml.sax.SAXException {
  }

  public void serializeURIs(net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.XMLSerializer context)
      throws org.xml.sax.SAXException {
  }

  public java.lang.Class getPrimaryInterface() {
    return (net.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeWithInnerClassType.class);
  }

  public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
    if (schemaFragment == null) {
      schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer
          .deserialize(("\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
              + "n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
              + "mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
              + "on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
              + "expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'com.sun.msv.grammar."
              + "trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/gr"
              + "ammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
              + "\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000s"
              + "q\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLor"
              + "g/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun"
              + "/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000#com.sun.msv.datatype.xsd.St"
              + "ringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.datatype."
              + "xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd"
              + ".ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatat"
              + "ypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btyp"
              + "eNameq\u0000~\u0000\u0015L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpa"
              + "ceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006stringsr"
              + "\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000"
              + "\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000"
              + "\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetExpression"
              + "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000"
              + "\u0002L\u0000\tlocalNameq\u0000~\u0000\u0015L\u0000\fnamespaceURIq\u0000~\u0000\u0015xpq\u0000~\u0000\u0019q\u0000~\u0000\u0018sr\u0000\u001dcom.su"
              + "n.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv.gr"
              + "ammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\txq\u0000"
              + "~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\rppsr\u0000\"c"
              + "om.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0012q\u0000~\u0000\u0018t\u0000\u0005QN"
              + "amesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse"
              + "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001bq\u0000~\u0000\u001esq\u0000~\u0000\u001fq\u0000~\u0000*q\u0000~\u0000\u0018sr\u0000#com.sun.msv.gramma"
              + "r.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0015L\u0000\fnamespaceURI"
              + "q\u0000~\u0000\u0015xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000"
              + ")http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.gr"
              + "ammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000%\u0001ps"
              + "q\u0000~\u0000.t\u0000\tFirstNamet\u0000\u0000sq\u0000~\u0000!ppsq\u0000~\u0000\bq\u0000~\u0000&p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\rppsr\u0000"
              + "!com.sun.msv.datatype.xsd.DateType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000)com.sun.msv"
              + ".datatype.xsd.DateTimeBaseType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u0000\u0012q\u0000~\u0000\u0018t\u0000\u0004dateq"
              + "\u0000~\u0000,q\u0000~\u0000\u001esq\u0000~\u0000\u001fq\u0000~\u0000@q\u0000~\u0000\u0018sq\u0000~\u0000!ppsq\u0000~\u0000#q\u0000~\u0000&pq\u0000~\u0000\'q\u0000~\u00000q\u0000~\u00004"
              + "sq\u0000~\u0000.t\u0000\tBirthDateq\u0000~\u00008q\u0000~\u00004sq\u0000~\u0000\bpp\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0010sq\u0000~\u0000!ppsq"
              + "\u0000~\u0000#q\u0000~\u0000&pq\u0000~\u0000\'q\u0000~\u00000q\u0000~\u00004sq\u0000~\u0000.t\u0000\bLastNameq\u0000~\u00008sq\u0000~\u0000\bpp\u0000sq\u0000~"
              + "\u0000\u0000ppsq\u0000~\u0000\bpp\u0000sq\u0000~\u0000!ppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000"
              + "\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~"
              + "\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000&psq\u0000~\u0000#q\u0000~\u0000&psr\u00002com.sun.msv.grammar.Expression"
              + "$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u00005psr\u0000 com.sun.msv.g"
              + "rammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000/q\u0000~\u00004sq\u0000~\u0000.t\u0000Qnet.sf.doz"
              + "er.util.mapping.vo.jaxb.employee.EmployeeWithInnerClassType."
              + "AddressTypet\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000"
              + "~\u0000!ppsq\u0000~\u0000#q\u0000~\u0000&pq\u0000~\u0000\'q\u0000~\u00000q\u0000~\u00004sq\u0000~\u0000.t\u0000\u0007Addressq\u0000~\u00008sr\u0000\"com"
              + ".sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom"
              + "/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv"
              + ".grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstre"
              + "amVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000"
              + "\u0000\u0000\u000e\u0001pq\u0000~\u0000;q\u0000~\u0000\u0006q\u0000~\u0000Oq\u0000~\u0000Mq\u0000~\u0000Rq\u0000~\u0000\u0005q\u0000~\u00009q\u0000~\u0000\"q\u0000~\u0000Bq\u0000~\u0000Hq\u0000~\u0000["
              + "q\u0000~\u0000\fq\u0000~\u0000Gq\u0000~\u0000\u0007x"));
    }
    return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
  }

  public static class AddressTypeImpl implements net.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeWithInnerClassType.AddressType,
      com.sun.xml.bind.JAXBObject, net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.UnmarshallableObject,
      net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.XMLSerializable,
      net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.ValidatableObject {

    protected java.lang.String _Street;
    public final static java.lang.Class version = (net.sf.dozer.util.mapping.vo.jaxb.employee.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
      return (net.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeWithInnerClassType.AddressType.class);
    }

    public java.lang.String getStreet() {
      return _Street;
    }

    public void setStreet(java.lang.String value) {
      _Street = value;
    }

    public net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.UnmarshallingEventHandler createUnmarshaller(
        net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.UnmarshallingContext context) {
      return new net.sf.dozer.util.mapping.vo.jaxb.employee.impl.EmployeeWithInnerClassTypeImpl.AddressTypeImpl.Unmarshaller(
          context);
    }

    public void serializeBody(net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException {
      context.startElement("", "Street");
      context.endNamespaceDecls();
      context.endAttributes();
      try {
        context.text(((java.lang.String) _Street), "Street");
      } catch (java.lang.Exception e) {
        net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.Util.handlePrintConversionException(this, e, context);
      }
      context.endElement();
    }

    public void serializeAttributes(net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException {
    }

    public void serializeURIs(net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException {
    }

    public java.lang.Class getPrimaryInterface() {
      return (net.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeWithInnerClassType.AddressType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
      if (schemaFragment == null) {
        schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer
            .deserialize(("\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
                + "\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
                + "grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
                + "\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
                + "msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Lj"
                + "ava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xppp\u0000sr\u0000\u001fcom.sun.msv.gra"
                + "mmar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp"
                + "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~\u0000\u0004ppsr\u0000\u001bcom.sun.msv.g"
                + "rammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datat"
                + "ype;L\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000"
                + "~\u0000\u0004ppsr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\ris"
                + "AlwaysValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000"
                + "\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
                + "xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnam"
                + "espaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000\u0012L\u0000\nwhiteSpacet"
                + "\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://"
                + "www.w3.org/2001/XMLSchemat\u0000\u0006stringsr\u00005com.sun.msv.datatype.x"
                + "sd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.da"
                + "tatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv."
                + "grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004ppsr\u0000\u001bc"
                + "om.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0012L\u0000\fnam"
                + "espaceURIq\u0000~\u0000\u0012xpq\u0000~\u0000\u0016q\u0000~\u0000\u0015sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000"
                + "\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\bppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000"
                + "\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004sr\u0000\u0011java.lang.Boolean"
                + "\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\nppsr\u0000\"com.sun.msv.datatype.xsd."
                + "QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u000fq\u0000~\u0000\u0015t\u0000\u0005QNamesr\u00005com.sun.msv.datat"
                + "ype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0018q\u0000~\u0000\u001bsq"
                + "\u0000~\u0000\u001cq\u0000~\u0000\'q\u0000~\u0000\u0015sr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
                + "\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0012L\u0000\fnamespaceURIq\u0000~\u0000\u0012xr\u0000\u001dcom.sun.msv.gra"
                + "mmar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/"
                + "XMLSchema-instancesr\u00000com.sun.msv.grammar.Expression$Epsilon"
                + "Expression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004sq\u0000~\u0000\"\u0001psq\u0000~\u0000+t\u0000\u0006Streett\u0000\u0000sr\u0000\"com"
                + ".sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom"
                + "/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv"
                + ".grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstre"
                + "amVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000"
                + "\u0000\u0000\u0002\u0001pq\u0000~\u0000\u001fq\u0000~\u0000\tx"));
      }
      return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller extends net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.AbstractUnmarshallingEventHandlerImpl {

      public Unmarshaller(net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.UnmarshallingContext context) {
        super(context, "----");
      }

      protected Unmarshaller(net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.UnmarshallingContext context, int startState) {
        this(context);
        state = startState;
      }

      public java.lang.Object owner() {
        return net.sf.dozer.util.mapping.vo.jaxb.employee.impl.EmployeeWithInnerClassTypeImpl.AddressTypeImpl.this;
      }

      public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname,
          org.xml.sax.Attributes __atts) throws org.xml.sax.SAXException {
        int attIdx;
        outer: while (true) {
          switch (state) {
          case 0:
            if (("Street" == ___local) && ("" == ___uri)) {
              context.pushAttributes(__atts, true);
              state = 1;
              return;
            }
            break;
          case 3:
            revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
            return;
          }
          super.enterElement(___uri, ___local, ___qname, __atts);
          break;
        }
      }

      public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
          throws org.xml.sax.SAXException {
        int attIdx;
        outer: while (true) {
          switch (state) {
          case 2:
            if (("Street" == ___local) && ("" == ___uri)) {
              context.popAttributes();
              state = 3;
              return;
            }
            break;
          case 3:
            revertToParentFromLeaveElement(___uri, ___local, ___qname);
            return;
          }
          super.leaveElement(___uri, ___local, ___qname);
          break;
        }
      }

      public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
          throws org.xml.sax.SAXException {
        int attIdx;
        outer: while (true) {
          switch (state) {
          case 3:
            revertToParentFromEnterAttribute(___uri, ___local, ___qname);
            return;
          }
          super.enterAttribute(___uri, ___local, ___qname);
          break;
        }
      }

      public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
          throws org.xml.sax.SAXException {
        int attIdx;
        outer: while (true) {
          switch (state) {
          case 3:
            revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
            return;
          }
          super.leaveAttribute(___uri, ___local, ___qname);
          break;
        }
      }

      public void handleText(final java.lang.String value) throws org.xml.sax.SAXException {
        int attIdx;
        outer: while (true) {
          try {
            switch (state) {
            case 1:
              eatText1(value);
              state = 2;
              return;
            case 3:
              revertToParentFromText(value);
              return;
            }
          } catch (java.lang.RuntimeException e) {
            handleUnexpectedTextException(value, e);
          }
          break;
        }
      }

      private void eatText1(final java.lang.String value) throws org.xml.sax.SAXException {
        try {
          _Street = value;
        } catch (java.lang.Exception e) {
          handleParseConversionException(e);
        }
      }

    }

  }

  public class Unmarshaller extends net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.AbstractUnmarshallingEventHandlerImpl {

    public Unmarshaller(net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.UnmarshallingContext context) {
      super(context, "-------------");
    }

    protected Unmarshaller(net.sf.dozer.util.mapping.vo.jaxb.employee.impl.runtime.UnmarshallingContext context, int startState) {
      this(context);
      state = startState;
    }

    public java.lang.Object owner() {
      return net.sf.dozer.util.mapping.vo.jaxb.employee.impl.EmployeeWithInnerClassTypeImpl.this;
    }

    public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname,
        org.xml.sax.Attributes __atts) throws org.xml.sax.SAXException {
      int attIdx;
      outer: while (true) {
        switch (state) {
        case 3:
          if (("BirthDate" == ___local) && ("" == ___uri)) {
            context.pushAttributes(__atts, true);
            state = 4;
            return;
          }
          state = 6;
          continue outer;
        case 12:
          revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
          return;
        case 6:
          if (("LastName" == ___local) && ("" == ___uri)) {
            context.pushAttributes(__atts, true);
            state = 7;
            return;
          }
          break;
        case 0:
          if (("FirstName" == ___local) && ("" == ___uri)) {
            context.pushAttributes(__atts, true);
            state = 1;
            return;
          }
          break;
        case 10:
          if (("Street" == ___local) && ("" == ___uri)) {
            _Address = ((net.sf.dozer.util.mapping.vo.jaxb.employee.impl.EmployeeWithInnerClassTypeImpl.AddressTypeImpl) spawnChildFromEnterElement(
                (net.sf.dozer.util.mapping.vo.jaxb.employee.impl.EmployeeWithInnerClassTypeImpl.AddressTypeImpl.class), 11, ___uri,
                ___local, ___qname, __atts));
            return;
          }
          break;
        case 9:
          if (("Address" == ___local) && ("" == ___uri)) {
            context.pushAttributes(__atts, false);
            state = 10;
            return;
          }
          break;
        }
        super.enterElement(___uri, ___local, ___qname, __atts);
        break;
      }
    }

    public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
        throws org.xml.sax.SAXException {
      int attIdx;
      outer: while (true) {
        switch (state) {
        case 8:
          if (("LastName" == ___local) && ("" == ___uri)) {
            context.popAttributes();
            state = 9;
            return;
          }
          break;
        case 3:
          state = 6;
          continue outer;
        case 12:
          revertToParentFromLeaveElement(___uri, ___local, ___qname);
          return;
        case 11:
          if (("Address" == ___local) && ("" == ___uri)) {
            context.popAttributes();
            state = 12;
            return;
          }
          break;
        case 2:
          if (("FirstName" == ___local) && ("" == ___uri)) {
            context.popAttributes();
            state = 3;
            return;
          }
          break;
        case 5:
          if (("BirthDate" == ___local) && ("" == ___uri)) {
            context.popAttributes();
            state = 6;
            return;
          }
          break;
        }
        super.leaveElement(___uri, ___local, ___qname);
        break;
      }
    }

    public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
        throws org.xml.sax.SAXException {
      int attIdx;
      outer: while (true) {
        switch (state) {
        case 3:
          state = 6;
          continue outer;
        case 12:
          revertToParentFromEnterAttribute(___uri, ___local, ___qname);
          return;
        }
        super.enterAttribute(___uri, ___local, ___qname);
        break;
      }
    }

    public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
        throws org.xml.sax.SAXException {
      int attIdx;
      outer: while (true) {
        switch (state) {
        case 3:
          state = 6;
          continue outer;
        case 12:
          revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
          return;
        }
        super.leaveAttribute(___uri, ___local, ___qname);
        break;
      }
    }

    public void handleText(final java.lang.String value) throws org.xml.sax.SAXException {
      int attIdx;
      outer: while (true) {
        try {
          switch (state) {
          case 3:
            state = 6;
            continue outer;
          case 12:
            revertToParentFromText(value);
            return;
          case 7:
            eatText1(value);
            state = 8;
            return;
          case 4:
            eatText2(value);
            state = 5;
            return;
          case 1:
            eatText3(value);
            state = 2;
            return;
          }
        } catch (java.lang.RuntimeException e) {
          handleUnexpectedTextException(value, e);
        }
        break;
      }
    }

    private void eatText1(final java.lang.String value) throws org.xml.sax.SAXException {
      try {
        _LastName = value;
      } catch (java.lang.Exception e) {
        handleParseConversionException(e);
      }
    }

    private void eatText2(final java.lang.String value) throws org.xml.sax.SAXException {
      try {
        _BirthDate = javax.xml.bind.DatatypeConverter.parseDate(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
      } catch (java.lang.Exception e) {
        handleParseConversionException(e);
      }
    }

    private void eatText3(final java.lang.String value) throws org.xml.sax.SAXException {
      try {
        _FirstName = value;
      } catch (java.lang.Exception e) {
        handleParseConversionException(e);
      }
    }

  }

}
