//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.05 at 10:03:40 CEST 
//

package net.sf.dozer.vo.jaxb.employee;

/**
 * Java content class for EmployeeWithInnerClass element declaration.
 * <p>
 * The following schema fragment specifies the expected content contained within this java content object. (defined at
 * file:/C:/Tools/dozer-2.3-src/dozer/dozer-src/etc/Employee.xsd line 12)
 * <p>
 * 
 * <pre>
 * &lt;element name=&quot;EmployeeWithInnerClass&quot;&gt;
 *   &lt;complexType&gt;
 *     &lt;complexContent&gt;
 *       &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *         &lt;sequence&gt;
 *           &lt;element name=&quot;FirstName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *           &lt;element name=&quot;BirthDate&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}date&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element name=&quot;LastName&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *           &lt;element name=&quot;Address&quot;&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name=&quot;Street&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/sequence&gt;
 *       &lt;/restriction&gt;
 *     &lt;/complexContent&gt;
 *   &lt;/complexType&gt;
 * &lt;/element&gt;
 * </pre>
 * 
 */
public interface EmployeeWithInnerClass extends javax.xml.bind.Element, net.sf.dozer.vo.jaxb.employee.EmployeeWithInnerClassType {

}
