== Support
=== Looking for support or want to propose an enhancement for the dozer Framework?
For community support or dozer enhancement requests check out the
https://groups.google.com/forum/?fromgroups#!forum/dozer-mapper[Google
Group] . We value your enhancement suggestions and want to build
something of value to the Java community. When submitting bug and
feature requests, it is really helpful if you are able to submit a
simplified unit test case(s) that reproduce the issue. We understand
this is not possible for every request, but if you are able to submit a
unit test it usually results in the request being implemented sooner.

=== Think you've found a bug?
Please enter a bug in the
https://github.com/DozerMapper/dozer/issues[GitHub Issue Tracker]. We
value your support there. We can't fix bugs we don't know about!

=== Have a feature request?
Please enter a feature request in the
link:https://github.com/DozerMapper/dozer/issues[GitHub Issue Tracker]. It
helps if you attach a pull request :)

=== Got a patch?
Please submit a pull request for Dozer GitHub project. Along with your
pull request we need a unit test and any supporting objects and mapping
file.
