//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.05 at 10:03:40 CEST 
//

package org.dozer.vo.jaxb.employee.impl;

public class EmployeeWithInnerClassImpl extends org.dozer.vo.jaxb.employee.impl.EmployeeWithInnerClassTypeImpl implements
    org.dozer.vo.jaxb.employee.EmployeeWithInnerClass, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject,
    org.dozer.vo.jaxb.employee.impl.runtime.UnmarshallableObject, org.dozer.vo.jaxb.employee.impl.runtime.XMLSerializable,
    org.dozer.vo.jaxb.employee.impl.runtime.ValidatableObject {

  public final static java.lang.Class version = (org.dozer.vo.jaxb.employee.impl.JAXBVersion.class);
  private static com.sun.msv.grammar.Grammar schemaFragment;

  private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
    return (org.dozer.vo.jaxb.employee.EmployeeWithInnerClass.class);
  }

  public java.lang.String ____jaxb_ri____getNamespaceURI() {
    return "http://jaxb.vo..dozer.sf.net/Employee";
  }

  public java.lang.String ____jaxb_ri____getLocalName() {
    return "EmployeeWithInnerClass";
  }

  @Override
  public org.dozer.vo.jaxb.employee.impl.runtime.UnmarshallingEventHandler createUnmarshaller(
      org.dozer.vo.jaxb.employee.impl.runtime.UnmarshallingContext context) {
    return new org.dozer.vo.jaxb.employee.impl.EmployeeWithInnerClassImpl.Unmarshaller(context);
  }

  @Override
  public void serializeBody(org.dozer.vo.jaxb.employee.impl.runtime.XMLSerializer context) throws org.xml.sax.SAXException {
    context.startElement("http://jaxb.vo..dozer.sf.net/Employee", "EmployeeWithInnerClass");
    super.serializeURIs(context);
    context.endNamespaceDecls();
    super.serializeAttributes(context);
    context.endAttributes();
    super.serializeBody(context);
    context.endElement();
  }

  @Override
  public void serializeAttributes(org.dozer.vo.jaxb.employee.impl.runtime.XMLSerializer context) throws org.xml.sax.SAXException {
  }

  @Override
  public void serializeURIs(org.dozer.vo.jaxb.employee.impl.runtime.XMLSerializer context) throws org.xml.sax.SAXException {
  }

  @Override
  public java.lang.Class getPrimaryInterface() {
    return (org.dozer.vo.jaxb.employee.EmployeeWithInnerClass.class);
  }

  @Override
  public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
    if (schemaFragment == null) {
      schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer
          .deserialize(("\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
              + "\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
              + "grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
              + "\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
              + "msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Lj"
              + "ava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xppp\u0000sr\u0000\u001fcom.sun.msv.gra"
              + "mmar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp"
              + "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~\u0000\u0004ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007pps"
              + "q\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000"
              + "\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0003L"
              + "\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0004ppsr\u0000#com.sun.ms"
              + "v.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com."
              + "sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun"
              + ".msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.dat"
              + "atype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/l"
              + "ang/String;L\u0000\btypeNameq\u0000~\u0000\u0017L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/data"
              + "type/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XML"
              + "Schemat\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProces"
              + "sor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpa"
              + "ceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$"
              + "NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004ppsr\u0000\u001bcom.sun.msv.util.Str"
              + "ingPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0017L\u0000\fnamespaceURIq\u0000~\u0000\u0017xpq\u0000~"
              + "\u0000\u001bq\u0000~\u0000\u001asr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\bpps"
              + "r\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0003L\u0000\t"
              + "nameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005value"
              + "xp\u0000psq\u0000~\u0000\u000fppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
              + "\u0000xq\u0000~\u0000\u0014q\u0000~\u0000\u001at\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceP"
              + "rocessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001dq\u0000~\u0000 sq\u0000~\u0000!q\u0000~\u0000,q\u0000~\u0000\u001asr\u0000#c"
              + "om.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~"
              + "\u0000\u0017L\u0000\fnamespaceURIq\u0000~\u0000\u0017xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000"
              + "\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-instances"
              + "r\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
              + "\u0000\u0000xq\u0000~\u0000\u0004sq\u0000~\u0000\'\u0001psq\u0000~\u00000t\u0000\tFirstNamet\u0000\u0000sq\u0000~\u0000#ppsq\u0000~\u0000\u0000q\u0000~\u0000(p\u0000sq"
              + "\u0000~\u0000\u0007ppsq\u0000~\u0000\u000fppsr\u0000!com.sun.msv.datatype.xsd.DateType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
              + "\u0000\u0000xr\u0000)com.sun.msv.datatype.xsd.DateTimeBaseType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq"
              + "\u0000~\u0000\u0014q\u0000~\u0000\u001at\u0000\u0004dateq\u0000~\u0000.q\u0000~\u0000 sq\u0000~\u0000!q\u0000~\u0000Bq\u0000~\u0000\u001asq\u0000~\u0000#ppsq\u0000~\u0000%q\u0000~\u0000"
              + "(pq\u0000~\u0000)q\u0000~\u00002q\u0000~\u00006sq\u0000~\u00000t\u0000\tBirthDateq\u0000~\u0000:q\u0000~\u00006sq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007"
              + "ppq\u0000~\u0000\u0012sq\u0000~\u0000#ppsq\u0000~\u0000%q\u0000~\u0000(pq\u0000~\u0000)q\u0000~\u00002q\u0000~\u00006sq\u0000~\u00000t\u0000\bLastNameq"
              + "\u0000~\u0000:sq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000#ppsr\u0000 com.sun.msv.gramma"
              + "r.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000"
              + "\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004q\u0000~\u0000(psq\u0000~\u0000%q\u0000~\u0000(psr\u00002com.sun.msv.g"
              + "rammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004q\u0000~\u00007p"
              + "sr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00001q\u0000~\u00006sq"
              + "\u0000~\u00000t\u0000Qnet.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeWi"
              + "thInnerClassType.AddressTypet\u0000+http://java.sun.com/jaxb/xjc/"
              + "dummy-elementssq\u0000~\u0000#ppsq\u0000~\u0000%q\u0000~\u0000(pq\u0000~\u0000)q\u0000~\u00002q\u0000~\u00006sq\u0000~\u00000t\u0000\u0007Ad"
              + "dressq\u0000~\u0000:sq\u0000~\u0000#ppsq\u0000~\u0000%q\u0000~\u0000(pq\u0000~\u0000)q\u0000~\u00002q\u0000~\u00006sq\u0000~\u00000t\u0000\u0016Employ"
              + "eeWithInnerClasst\u00001http://jaxb.vo..dozer.sf.net/"
              + "Employeesr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\b"
              + "expTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xp"
              + "sr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003"
              + "I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/Exp"
              + "ressionPool;xp\u0000\u0000\u0000\u0010\u0001pq\u0000~\u0000=q\u0000~\u0000\u000bq\u0000~\u0000Qq\u0000~\u0000\tq\u0000~\u0000Oq\u0000~\u0000Tq\u0000~\u0000\nq\u0000~\u0000;"
              + "q\u0000~\u0000$q\u0000~\u0000Dq\u0000~\u0000Jq\u0000~\u0000]q\u0000~\u0000\u000eq\u0000~\u0000Iq\u0000~\u0000aq\u0000~\u0000\fx"));
    }
    return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
  }

  public class Unmarshaller extends org.dozer.vo.jaxb.employee.impl.runtime.AbstractUnmarshallingEventHandlerImpl {

    public Unmarshaller(org.dozer.vo.jaxb.employee.impl.runtime.UnmarshallingContext context) {
      super(context, "----");
    }

    protected Unmarshaller(org.dozer.vo.jaxb.employee.impl.runtime.UnmarshallingContext context, int startState) {
      this(context);
      state = startState;
    }

    public java.lang.Object owner() {
      return org.dozer.vo.jaxb.employee.impl.EmployeeWithInnerClassImpl.this;
    }

    @Override
    public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname,
        org.xml.sax.Attributes __atts) throws org.xml.sax.SAXException {
      outer: while (true) {
        switch (state) {
        case 1:
          if (("FirstName" == ___local) && ("" == ___uri)) {
            spawnHandlerFromEnterElement(
                (((org.dozer.vo.jaxb.employee.impl.EmployeeWithInnerClassTypeImpl) org.dozer.vo.jaxb.employee.impl.EmployeeWithInnerClassImpl.this).new Unmarshaller(
                    context)), 2, ___uri, ___local, ___qname, __atts);
            return;
          }
          break;
        case 3:
          revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
          return;
        case 0:
          if (("EmployeeWithInnerClass" == ___local) && ("http://jaxb.vo..dozer.sf.net/Employee" == ___uri)) {
            context.pushAttributes(__atts, false);
            state = 1;
            return;
          }
          break;
        }
        super.enterElement(___uri, ___local, ___qname, __atts);
        break;
      }
    }

    @Override
    public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
        throws org.xml.sax.SAXException {
      outer: while (true) {
        switch (state) {
        case 2:
          if (("EmployeeWithInnerClass" == ___local) && ("http://jaxb.vo..dozer.sf.net/Employee" == ___uri)) {
            context.popAttributes();
            state = 3;
            return;
          }
          break;
        case 3:
          revertToParentFromLeaveElement(___uri, ___local, ___qname);
          return;
        }
        super.leaveElement(___uri, ___local, ___qname);
        break;
      }
    }

    @Override
    public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
        throws org.xml.sax.SAXException {
      outer: while (true) {
        switch (state) {
        case 3:
          revertToParentFromEnterAttribute(___uri, ___local, ___qname);
          return;
        }
        super.enterAttribute(___uri, ___local, ___qname);
        break;
      }
    }

    @Override
    public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
        throws org.xml.sax.SAXException {
      outer: while (true) {
        switch (state) {
        case 3:
          revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
          return;
        }
        super.leaveAttribute(___uri, ___local, ___qname);
        break;
      }
    }

    @Override
    public void handleText(final java.lang.String value) throws org.xml.sax.SAXException {
      outer: while (true) {
        try {
          switch (state) {
          case 3:
            revertToParentFromText(value);
            return;
          }
        } catch (java.lang.RuntimeException e) {
          handleUnexpectedTextException(value, e);
        }
        break;
      }
    }

  }

}
