//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.05 at 10:03:40 CEST 
//

package org.dozer.vo.jaxb.employee.impl.runtime;

import javax.xml.bind.UnmarshallerHandler;
import javax.xml.bind.ValidationEvent;

import org.xml.sax.SAXException;

/**
 * Unified event handler that processes both the SAX events and error events.
 * 
 * <p>
 * This interface refines {@link ContentHandler} as follows:
 * <ol>
 * <li>element names and attribute names must be {@link String#intern()}ed.
 * <li>namespace prefix and uris must be {@link String#intern()}ed.
 * </ol>
 */
public interface SAXUnmarshallerHandler extends UnmarshallerHandler {

  /**
   * Reports an error to the user, and asks if s/he wants to recover. If the canRecover flag is false, regardless of the
   * client instruction, an exception will be thrown.
   * 
   * Only if the flag is true and the user wants to recover from an error, the method returns normally.
   * 
   * The thrown exception will be catched by the unmarshaller.
   */
  void handleEvent(ValidationEvent event, boolean canRecover) throws SAXException;
}
