== Migration from v6.1.0 to v6.2.0
See link:https://github.com/DozerMapper/dozer/releases/tag/6.2.0[for release notes].

=== 1. JMX/Stats has been removed
As per 6.1.0 migration docs, JMX and Stats were deprecated. They have now been fully removed.

=== 2. dozer.properties keys changed
**From:**
[source,prettyprint]
----
    dozer.cache.converter.by.dest.type.maxsize
    dozer.cache.super.type.maxsize
    org.dozer.util.DozerClassLoader
    org.dozer.util.DozerProxyResolver
----

**To:**
[source,prettyprint]
----
    dozer.cache.converter-by-dest-type-maxsize
    dozer.cache.super-type-maxsize
    dozer.beans.class-loader-bean
    dozer.beans.proxy-resolver-bean
----

=== 3. Support for YAML, SystemProperties and Environment variables
As as well as dozer.properties, we also support several new implementations, such as YAML, see:
- https://github.com/DozerMapper/dozer/tree/6.2.0/core/src/main/java/org/dozer/config/resolvers
- https://github.com/DozerMapper/dozer/tree/6.2.0/core/src/main/java/org/dozer/config/processors

=== 4. dozer.el.enabled is deprecated
The property for 'dozer.el.enabled' has been deprecated. Instead, you should use:

[source,java,prettyprint]
----
    DefaultELEngine elEngine = new DefaultELEngine();
    Mapper mapper = DozerBeanMapperBuilder.create()
            .withMappingFiles(mappingFiles)
            .withElementReader(new ExpressionElementReader(elEngine))
            .withELEngine(elEngine)
            .build();
----

=== 5. Spring maven artifact name has changed
**From:**
[source,xml,prettyprint]
----
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-spring</artifactId>
    <version>6.1.0</version>
</dependency>
----

**To:**
[source,xml,prettyprint]
----
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-spring4</artifactId>
    <version>6.2.0</version>
</dependency>
----

=== 6. Spring maven artifact name has changed
**From:**
[source,xml,prettyprint]
----
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-proto</artifactId>
    <version>6.1.0</version>
</dependency>
----

**To:**
[source,xml,prettyprint]
----
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-proto3</artifactId>
    <version>6.2.0</version>
</dependency>
----

=== 7. Extended spring boot support
`dozer-spring-boot-starter` and `dozer-spring-boot-autoconfigure` artifacts added to support spring boot auto configuration features.

[source,xml,prettyprint]
----
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-spring-boot-starter</artifactId>
    <version>6.2.0</version>
</dependency>
----

=== 8. dozer.xml.use-jaxb-mapping-engine to use new JAXB
The current Dozer XML to Objects implementation uses org.w3c.dom.Document to parse the model.
Going forward, the intention is to use a JAXB model. This feature is not enabled by default, but can be via:

[source,prettyprint]
----
    dozer.xml.use-jaxb-mapping-engine=true
----
