//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.05 at 10:03:40 CEST 
//


package net.sf.dozer.util.mapping.vo.jaxb.employee;


/**
 * Java content class for Employee element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Tools/dozer-2.3-src/dozer/dozer-src/etc/Employee.xsd line 11)
 * <p>
 * <pre>
 * &lt;element name="Employee" type="{http://jaxb.vo.mapping.util.dozer.sf.net/Employee}EmployeeType"/>
 * </pre>
 * 
 */
public interface Employee
    extends javax.xml.bind.Element, net.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeType
{


}
