//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.05 at 10:03:40 CEST 
//


package net.sf.dozer.util.mapping.vo.jaxb.employee;


/**
 * Java content class for EmployeeWithInnerClass element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Tools/dozer-2.3-src/dozer/dozer-src/etc/Employee.xsd line 12)
 * <p>
 * <pre>
 * &lt;element name="EmployeeWithInnerClass">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *           &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Address">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Street" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface EmployeeWithInnerClass
    extends javax.xml.bind.Element, net.sf.dozer.util.mapping.vo.jaxb.employee.EmployeeWithInnerClassType
{


}
